import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens (Vivu Discovery palette)
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#005cba',
        'on-surface': '#191c1d',
        'on-surface-variant': '#414753',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#727784',
        'outline-variant': '#c1c6d5',
        primary: '#004e9f',
        'on-primary': '#ffffff',
        'primary-container': '#0066cc',
        'on-primary-container': '#dfe8ff',
        'inverse-primary': '#aac7ff',
        'primary-fixed': '#d7e3ff',
        'primary-fixed-dim': '#aac7ff',
        'on-primary-fixed': '#001b3e',
        'on-primary-fixed-variant': '#00458e',
        secondary: '#566068',
        'on-secondary': '#ffffff',
        'secondary-container': '#dae4ee',
        'on-secondary-container': '#5c666e',
        'secondary-fixed': '#dae4ee',
        'secondary-fixed-dim': '#bec8d1',
        'on-secondary-fixed': '#131d24',
        'on-secondary-fixed-variant': '#3e4850',
        tertiary: '#00528f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006ab8',
        'on-tertiary-container': '#dbe9ff',
        'tertiary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#a1c9ff',
        'on-tertiary-fixed': '#001c37',
        'on-tertiary-fixed-variant': '#004880',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9fa',
        'on-background': '#191c1d',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-be-vietnam-pro)', 'system-ui', 'sans-serif'],
        h1: ['var(--font-be-vietnam-pro)', 'system-ui', 'sans-serif'],
        h2: ['var(--font-be-vietnam-pro)', 'system-ui', 'sans-serif'],
        h3: ['var(--font-be-vietnam-pro)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'section-gap': '80px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        premium: '0 4px 20px rgba(0, 102, 204, 0.15)',
        hover: '0 8px 30px rgba(0, 102, 204, 0.2)',
      },
    },
  },
  plugins: [],
};

export default config;
